spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=czestochowabuild@gmail.com
spring.mail.password=dhlz nsqi wctv anty
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.datasource.url=jdbc:postgresql://dpg-d7021dnafjfc73asml0g-a.oregon-postgres.render.com:5432/build_32yb
spring.datasource.username=build_32yb_user
spring.datasource.password=4hfCc6hgKeTsJEqPqFT3eFcgmqfrxXUw

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:5432}